Convert chapters 11 & 15 of Pacemaker Explained to rst
ClusterLabs/pacemaker pull request #2197
Opened 2020-10-20 14:08 UTC by clumens

2020-10-20 19:29 UTC, kgaillot requested changes
I can see the light at the end of the tunnel :)

2020-10-20 19:29 UTC, kgaillot commented on doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
> +the primitive has an additional +stop+ operation.
s/+/``/

2020-10-20 19:29 UTC, kgaillot commented on doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
> +would colocate all VMs with +base-rsc+ and is the equivalent of the following constraint configuration:
s/+/``/

2020-10-20 19:29 UTC, kgaillot commented on doc/sphinx/Pacemaker_Explained/reusing-configuration.rst
> +do with tags mostly depends on the tools you use.
Might as well update this section to reference crm_mon --resource/--node (probably in its own commit)

2020-10-20 19:29 UTC, kgaillot commented on doc/sphinx/Pacemaker_Explained/multi-site-clusters.rst
> +Display the +rsc_ticket+ constraints that apply to a ticket:
s/+/``/

2020-10-20 19:29 UTC, kgaillot commented on doc/sphinx/Pacemaker_Explained/multi-site-clusters.rst
> +The proper way is making the ticket 'standby' first with:
s/'/*/

2020-10-20 20:22 UTC, clumens commented
Yep, we're getting close on it.  Only a couple chapters left and we can stop worrying about sphinx.

2020-10-22 19:27 UTC, kgaillot approved these changes

2020-10-22 19:27 UTC, merged