add zh_CN translations for fenced file
ClusterLabs/pacemaker pull request #2884
Opened 2022-09-22 13:03 UTC by bin-ly

Supplement the translation of fenced file.

2022-09-22 16:44 UTC, kgaillot reviewed
Hi,

Thanks for this submission. I noticed a few spots that look off.

Also, I noticed some places where the English string needs changes (mostly just spaces), but I guess we can revisit that in the future.

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +"`SBD_WATCGDOG_timeout`,如果本地值不是这样，或者SBD未激活，则起搏器将拒绝在任"
SBD_WATCHDOG_TIMEOUT

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +"提供任何其他的参数。"
'port' should be literal

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-22 16:44 UTC, kgaillot commented on po/zh_CN.po
> +msgstr "仅高级使用：指定用于on 操作的替代超时，而不是stonith-timeout"
This doesn't look like it matches up

2022-09-23 09:37 UTC, gao-yan requested changes
Thanks. Some comments here.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"例如 node1为1;node2为2和3，将会告诉集群对node1使用端口1,对node2使用端口2和3 "
We should keep the configuration string `node1:1;node2:2,3` literal.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"一些设备不支持标准命令或可能提供其他命令使用此选项可指定一个备用的、特定于设"
Let's add a full stop "。" after "...其他命令".

“替代的” rather than "备用的".

And it  should be better with something like "该设备特定的" rather than “特定于设备”.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"一些设备需要比正常情况下更多或更少的时间来完成，使用此选项指定一个用"
"完成操作".

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"于'reboot'的备用的、特定于设备的超时命令。"
Similarly something like： "... 用于 'reboot' 操作的该设备特定的替代超时".

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "仅高级使用：在超时前重试'off'命令的最大次数"
Probably due to wrong copy & paste :-) This should be about "替代命令".

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备的命令，用来实现'off'操作。"
Similarly as above.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备用的、特定于设备的超时命令。"
Similarly as above.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备的命令，用来实现'on'操作。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备用的、特定于设备的超时命令。"
Similarly

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备的命令，用来实现'list'操作。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"于'list'的备用的、特定于设备的超时命令。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备的命令，用来实现'monitor'操作。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"于'monitor'的备用的、特定于设备的超时命令。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"备的命令，用来实现'status'操作。"
Similarly.

2022-09-23 09:37 UTC, gao-yan commented on po/zh_CN.po
> +"于'status'的备用的、特定于设备的超时命令。"
Similarly.

2022-09-26 09:13 UTC, gao-yan approved these changes
Thanks for the revisions. Except a nitpicking, it looks good to me.

2022-09-26 17:25 UTC, kgaillot commented on po/zh_CN.po
> +"如果设置为正值，则假定丢失的节点在这段时间内使用基于看门狗的SBD进行自我防护。"
I'm fine with whatever you decide, but I'm curious whether translations of the kernel documentation have a preference when talking about watchdog devices.

2022-09-27 13:55 UTC, kgaillot commented
Thanks!

2022-09-27 13:55 UTC, merged