Synchronous Chinese translation
ClusterLabs/pacemaker pull request #2891
Opened 2022-09-28 10:07 UTC by LiHaiP

2022-09-28 10:44 UTC, gao-yan requested changes

2022-09-28 10:44 UTC, gao-yan commented on po/zh_CN.po
> +"***不推荐***是否删除资源管理器中已停止的资源"
Let's be more precise like "是否从 pacemaker-execd 守护进程中清除已停止的资源".

2022-09-28 10:44 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "是否停止删除配置的资源"
Or should be more clear to go with "配置已被删除的资源"?

2022-09-28 10:44 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "是否取消删除配置的重复操作"
Similarly.

2022-09-28 14:10 UTC, kgaillot commented
ok to test

2022-10-10 10:37 UTC, gao-yan requested changes

2022-10-10 10:37 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "配置已被删除的资源"
Of course to be complete, it should be like "是否停止配置已被删除的资源".

2022-10-10 10:37 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "是否取消删除配置的重复操作"
So this could be "是否取消配置已被删除的的重复操作".

2022-10-12 07:51 UTC, gao-yan commented
We could avoid such a "Merge" commit, for example with `git reset` and `amend` commands on the previously existing commit. And `git push --force` will update the PR.

2022-10-14 08:06 UTC, gao-yan commented
Thanks. It seems that you need to rebase your commit onto the main HEAD though.

2022-10-18 10:17 UTC, closed without merging