add zh_CN translation for pacemaker-schedulerd libexec
ClusterLabs/pacemaker pull request #2932
Opened 2022-11-11 09:29 UTC by luckhuanhuan

2022-11-11 09:51 UTC, wenningerk commented
test this please

2022-11-11 13:21 UTC, gao-yan requested changes

2022-11-14 11:52 UTC, gao-yan approved these changes
Thanks.

2022-11-14 15:23 UTC, kgaillot commented
Thanks @luckhuanhuan and @gao-yan !

2022-11-14 15:23 UTC, merged