add zh_cn translation for error
ClusterLabs/pacemaker pull request #2941
Opened 2022-11-16 06:12 UTC by WangMengabc

2022-11-16 08:12 UTC, wenningerk commented
test this please

2022-11-16 12:17 UTC, gao-yan requested changes

2022-11-16 12:17 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "无法创建资源程序链接"
The term "executor" is translated/interpreted to "pacemaker-execd 守护进程" in other places:

https://github.com/ClusterLabs/pacemaker/commit/27a77334f4#diff-0a4a9ca503c41c5f2a54de36293d8863d6ef72d42476226fa0b9eddf52bc94e9R683

Please keep it consistent.

So this basically means "无法创建到 pacemaker-execd 守护进程的连接".

2022-11-16 12:17 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "不能创建CIB连接"
Should be better to be consistent with the above "Could not" case with something like "无法创建到 CIB 的连接".

2022-11-16 15:29 UTC, kgaillot commented
Hi,

Since these are command-line output messages, and not log messages, I'm OK with translating them, but I recommend thinking about whether it is worth it. Unlike the option descriptions, these messages are more likely to change from release to release, so it will require ongoing effort to keep them up to date. With the small number of messages here, that wouldn't be significant, but if you plan on eventually translating all of them, it likely will be.

If you do want to proceed, please squash these commits into one, and rebase on current main to avoid the merge commit. Thanks!

2022-11-16 15:29 UTC, kgaillot commented
ok to test

2022-11-17 09:14 UTC, wenningerk commented
Still looking as if you have multiple commits on your branch.
A little bit unfortunate that you were working on the main.

I personally keep the official branches as is, both on my
clone on github as well as my local clones. That makes it
easy to revert to main or pull current changes from upstream
into main.

If a local branch is messed up too much I usually stop messing
around with rebase (incl. squash) & reset but rather try to move
the changes cleanly into a new branch (squashing them before
or after depends on the situation and/or personal preferences)
and force push that to my work-branch on github.
Only bad impact of force-pushing to the branch the PR was
created for is that the discussion may look a bit messed up as
the commits referred to may be gone. Guess this is the reason
why some people prefer keeping the branch as is, close the
PR and create a new one for a new branch. In my eyes that
is just another kind of (depending on the volume of the discussion
supposedly bigger) mess.

2022-11-17 10:13 UTC, wenningerk commented
aah cool ... merge commits gone.
as I had understood Ken meant to squash the 2 code-commits on top.

2022-11-17 16:19 UTC, gao-yan requested changes

2022-11-17 16:19 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "%s不能连接到CIB"
Since `%s` is the error message, we could keep it like "不能连接到CIB： %s".

2022-11-17 16:19 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "不能操作克隆资源'%s'"
We should be more specific that this is about "克隆资源实例".

2022-11-17 16:19 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "未生效的命令：%d"
Could be better with "无效的命令".

2022-11-18 09:27 UTC, gao-yan commented on po/zh_CN.po
> +
Should be better with "'%s' 解析错误，格式为 name=value ".

2022-11-18 10:09 UTC, gao-yan approved these changes
Would be better to squash the additional commits for revisions into the previous.  The content looks good though..

2022-11-22 05:35 UTC, closed without merging