add zh_cn translation for error
ClusterLabs/pacemaker pull request #2957
Opened 2022-11-24 06:24 UTC by WangMengabc

translation   tools/crm_resource.c file error message

2022-11-24 09:21 UTC, wenningerk commented
test this please

2022-11-24 09:37 UTC, gao-yan requested changes
AFAICS, this basically is https://github.com/ClusterLabs/pacemaker/pull/2941 ? There's a regression here though compared with the other. Please check the inline comment.

BTW, I believe by arranging your local branch with "git reset" and "git commit --amend" commands, and then "git push " again, the other PR could have been updated ... For example like demonstrated here:

https://github.com/ClusterLabs/pacemaker/pull/2936#pullrequestreview-1184360641

But anyways, since you've already closed the other one and opened this, we can try to make it here :-)

For the future, a generally better idea is to create a separate local branch to work on your project and leave the main branch. So that in case rebase is needed, you will still have the clean main branch for fetching from the upstream.

2022-11-24 09:37 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "没有发现指定的'%s'标准代理"
Somehow this got imprecise anymore and basically it doesn't match the original format.

2022-11-24 09:49 UTC, gao-yan commented on po/zh_CN.po
> +"资源%s未移动，在%d个位置运行\n"
Better still use "：“ here.

2022-11-29 10:20 UTC, gao-yan approved these changes
LGTM.

2022-11-29 16:25 UTC, merged