Sync Chinese translation
ClusterLabs/pacemaker pull request #2980
Opened 2022-12-14 09:05 UTC by LiHaiP

2022-12-14 09:19 UTC, wenningerk commented
test this please

2022-12-14 12:33 UTC, gao-yan requested changes

2022-12-15 07:10 UTC, LiHaiP commented on po/zh_CN.po
> +"该选项将在未来的版本中删除。"
I agree with you and I will update

2022-12-15 13:52 UTC, gao-yan approved these changes
LGTM, thanks.

2022-12-15 15:04 UTC, kgaillot reviewed
Thanks for the updates! Would you mind rebasing this to avoid the merge commit? If you're not comfortable with git rebase commands, the simplest way may be to copy the changed files into a clean checkout.

2022-12-19 16:02 UTC, kgaillot commented
Hi @LiHaiP ,

This still has merge commits, which we prefer to avoid inside a pull request. Also, it's much simpler in the long run to work from a separate branch instead of making changes in the main branch. Here's one way to do that:

First, save the two files you changed so you don't lose your changes:

    mkdir ~/tmp
    cp lib/pengine/common.c ~/tmp
    cp po/zh_CN.po ~/tmp

Then, make your main branch the same as the upstream main branch:

    git remote add upstream https://github.com/ClusterLabs/pacemaker.git
    git reset --hard upstream/main
    git push origin +HEAD:main

Then, make your changes in a new branch, and push those to your pacemaker repository:

    git checkout -b changes
    mv ~/tmp/common.c lib/pengine/
    mv ~/tmp/zh_CN.po po/
    git add lib/pengine/common.c po/zh_CN.po
    git commit -m "Doc: scheduler: update Chinese translation"
    git push origin changes

Finally, you can close this pull request, and open a new one, selecting the "changes" branch from your repository.

While it's a lot this time, it will simplify any future changes you do. Whenever you need to make more changes, you can do your work in the changes branch. When needed, you can synchronize your main branch with upstream by running `git checkout main && git pull upstream main`, then update your changes branch with `git checkout changes && git rebase main` to avoid merge commits.

2022-12-21 06:33 UTC, closed without merging