Optimize some Chinese translations of the controld_control file
ClusterLabs/pacemaker pull request #3300
Opened 2023-12-28 06:40 UTC by daaitudian

Hi,
I have modified some Chinese translations to make them more fluent and understandable while retaining some proper nouns and symbols.

2024-01-03 22:31 UTC, kgaillot commented
Hi, just to let you know, PR #3297 included some changes to option descriptions.

2024-01-11 10:09 UTC, daaitudian commented
Thank you for your reminder. I will resubmit it after making modifications.

2024-01-11 16:49 UTC, kgaillot commented
Hi @daaitudian , I will likely merge #3311 today which consolidates all the cluster options in a single table. Most of the descriptions remain unchanged. Once that's merged, you can redo these changes on the updated files. Hopefully that will be the last changes for the near future.

2024-01-15 17:35 UTC, gao-yan requested changes
Thanks. Some points in below.

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"这个值如果设置为正值, 丢失的节点将在设定的时间内将被假设使用基于 "
How about "正数" given that "负数" is used later?

"被认定" should be better than "被假设" here for "assumed".

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"watchdog (watchdog-based)的SBD进行自我 fence (self-fencing)."
Similarly about "watchdog-based".

It's more precise with "完成了自我 fence" than "进行自我 fence".

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"这不需要明确配置一个隔离(fence)资源, 但可以配置一个 fence_watchdog "
So far "fence" has remained literal without being translated everywhere. Probably we should keep it consistent here as well.

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"资源来限制在特定节点上进行使用. 如果这个值设为0 (默认值), 集群将永远不会"
“来限制对特定节点使用”.

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"假定节点使用基于 watchdog (watchdog-based)的自我 fence(self-fencing)"
To be consistent, "认定".

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"(watchdog-based)的SBD的节点上, 此超时值需大于`SBD_WATCHDOG_TIMEOUT`"
Similarly about "watchdog-based".

2024-01-15 17:35 UTC, gao-yan commented on po/zh_CN.po
> +"的值, 否则Pacemaker将不会在任何不符合此条件的节点上启动. 当此值设为负数时"
We are missing the part: "也不会再任何未启用SBD的节点上运行"。

2024-01-15 18:20 UTC, kgaillot commented
@gao-yan , your review makes me realize the English wording is sometimes unclear on its own. If you want to point out where the English wording could be more specific and/or clear, I will come up with something that makes more sense, to make both English comprehension and translation easier

2024-01-16 07:57 UTC, closed without merging

2024-01-16 10:34 UTC, daaitudian commented
@kgaillot @gao-yan , Due to the current conflict, I have closed the current submission. I will submit a revised version based on your suggestions. Thanks for your help.

2024-01-16 13:50 UTC, gao-yan commented
> @gao-yan , your review makes me realize the English wording is sometimes unclear on its own. If you want to point out where the English wording could be more specific and/or clear, I will come up with something that makes more sense, to make both English comprehension and translation easier

Makes perfect sense. Here we go: https://github.com/ClusterLabs/pacemaker/pull/3325