Optimize some Chinese translations
ClusterLabs/pacemaker pull request #3353
Opened 2024-02-08 09:16 UTC by daaitudian

Hi @kgaillot @gao-yan:
I made some changes as suggested earlier.  #3300

2024-02-13 15:37 UTC, kgaillot commented
@daaitudian this will need a rebase on main, there was an unrelated change to the po file

2024-02-13 21:28 UTC, gao-yan requested changes
Thanks. Some points in below.

2024-02-20 03:36 UTC, daaitudian commented
> @daaitudian这需要对 main 进行变基，对 po 文件进行了不相关的更改

2024-02-20 03:37 UTC, daaitudian commented
> @daaitudian this will need a rebase on main, there was an unrelated change to the po file

I tried to perform a rebase operation, pulling all the new merges into my branch and then placing the translation modifications at the end. However, I'm not sure if my operation is correct. Please let me know if there are any issues.

2024-02-20 05:41 UTC, daaitudian commented
> Thanks. Some points in below.

@gao-yan Thank you for your advice. I have completed the modifications.

2024-02-22 12:55 UTC, gao-yan requested changes
Nice. Thanks for the update.

Only a few points that I also missed in the last round.

2024-02-22 12:55 UTC, gao-yan commented on po/zh_CN.po
> +"基于时间的规则以及 failure-timeout 配置, 然而无论如何, 在一段时间后如果没有活"
经过指定的时间后

2024-02-27 06:02 UTC, daaitudian commented
Thanks. I have completed the modifications.

2024-02-27 09:35 UTC, gao-yan reviewed
Nice update. Only one point.

2024-02-27 09:35 UTC, gao-yan commented on po/zh_CN.po
> +msgstr "在执行 fence 操作前启用不超过指定时间的延迟. "
Let's make this translation match the description for pcmk_delay_base again, something like ""为 fence 操作启用一个指定的基础延迟。"

2024-02-27 09:49 UTC, daaitudian commented on po/zh_CN.po
> +msgstr "在执行 fence 操作前启用不超过指定时间的延迟. "
Thanks.

2024-02-27 15:22 UTC, merged

2024-02-27 15:26 UTC, kgaillot commented
FYI, #3338 will make substantial changes to the option help. The most significant will be separating the advanced-use and deprecation notices into their own strings rather than add them as part of the option description. This is part of a project to be able to display the options in either readable text or XML format.