Consistently name constants defined in configure.ac
ClusterLabs/pacemaker pull request #3618
Opened 2024-08-19 16:04 UTC by clumens

2024-08-19 20:00 UTC, kgaillot requested changes
awesome, thanks

2024-08-19 20:13 UTC, clumens commented on include/crm/services.h
> -#  include <crm_config.h>       // OCF_ROOT_DIR
It's not actually used anywhere in this header and removing the include doesn't affect compliation, so the only reason to leave it around is for other projects.

2024-08-19 20:33 UTC, kgaillot commented on include/crm/services.h
> -#  include <crm_config.h>       // OCF_ROOT_DIR
Right, that's what API being public means :)

2024-08-20 14:43 UTC, kgaillot approved these changes

2024-08-20 18:25 UTC, merged