Fixed integer overflow at stonith_admin with -t options
ClusterLabs/pacemaker pull request #3768
Opened 2024-12-13 13:24 UTC by WhiteWLf-dev

2024-12-13 14:04 UTC, wenningerk commented on tools/stonith_admin.c
> +    }
Guess we should do the error output more inline with how it is done for other errors.
Is there a sense in a negative timeout?

2024-12-13 18:28 UTC, clumens commented
This is a little bit larger of a problem than it first appears.  We don't do a very good job of consistently handling timeouts in our command line tools - cibadmin, crm_resource, crmadmin, and stonith_admin all have a `--timeout` parameter and all handle things slightly differently.

We have a fairly old upstream issue for dealing with this inconsistency (https://projects.clusterlabs.org/T165) and there's been at least one stab at fixing the issue before.  I think it's about time we deal with that project.

2024-12-16 15:55 UTC, kgaillot requested changes
Thanks for catching this bug and many thanks for submitting a fix :)

We do need to make command-line timeout options more consistent, but this will be a good step in the meantime

2024-12-16 15:55 UTC, kgaillot commented on tools/stonith_admin.c
> +    if (options.timeout > INT_MAX / 1000 || options.timeout < INT_MIN / 1000) {
This is actually passed to functions as an `unsigned int` argument, so we should check

```
((options.timeout > (UINT_MAX / 1000)) || (options.timeout < 0))
```

2024-12-16 15:55 UTC, kgaillot commented on tools/stonith_admin.c
> +        printf("stonith_admin: Integer value \"%d\" for -t out of range\n", options.timeout);
Simply replace `printf` with `out->err` (that formats the message as text or XML depending on the value of `--output-as`)

We don't need the `stonith_admin: ` prefix

2024-12-16 15:55 UTC, kgaillot commented
ok to test

(that's for the automated CI testing)

2024-12-17 16:06 UTC, kgaillot reviewed
Looks great, thanks! I forgot one other change: could you update the commit message to "Fix: tools: validate stonith_admin --timeout value"? That way it will automatically land in the next release's ChangeLog.

2024-12-17 18:25 UTC, kgaillot approved these changes

2024-12-17 20:43 UTC, merged

2024-12-23 18:43 UTC, kgaillot commented
FYI, I backported this to the 3.0 branch for the forthcoming 3.0.0-rc3 release